color: null
fieldLayouts:
  aa4c47b7-7f84-4fc6-b5bf-8b753e8b921a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Homepage Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1978b04f-940c-4c46-93f7-2780ce58676e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 36d05999-7f67-4308-9244-582978fb678c # Subtitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8ef9123-be2c-4b74-b337-31402d90bce1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cfb22fa1-6f63-4abd-8430-0f423fd93511
        userCondition: null
handle: homepage
hasTitleField: true
icon: ''
name: Homepage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
