color: null
fieldLayouts:
  40ad5eab-ea11-457c-9171-200a6ae40d01:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dbb7918a-9778-4494-8f9e-e8e982eff404
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 95053f16-aaf0-4d78-b756-1b4871f0bebc # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 038255d9-4340-46bf-b7c6-06263a9c38b0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f1a8441d-e7da-431f-8aea-821774aa6852 # Image Caption
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb004c6a-6d77-4418-9a6e-e8e59cf58252
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 08d8da8e-6f50-445c-b7e7-0244bf171872
        userCondition: null
handle: recipeImage
hasTitleField: false
icon: ''
name: 'Recipe Image'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
