defaultPlacement: end
fieldLayouts:
  1c991681-f6ff-46eb-9f41-87207a084d4f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: d4c7359e-3169-4995-b43c-9a7c757acbf7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c130f4c5-0f8d-42e3-b1ac-afac0e8a6664 # Style Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf2df959-e38a-4960-8f44-a5d346a97624
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 555e9ebd-8fd5-4202-9c9f-b794912606c2
        userCondition: null
handle: drinkStyles
name: 'Drink Styles'
siteSettings:
  390b5f78-90ea-46fe-a0d3-31cfe4a41d7a: # My Example Craft Site
    hasUrls: true
    template: styles/_entry
    uriFormat: 'styles/{slug}'
structure:
  maxLevels: 5
  uid: 886268ca-db2f-4c6b-997a-16952d101204
