columnSuffix: null
handle: drinkImage
instructions: null
name: 'Drink Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:212dd363-6e33-43f3-8dc4-ba56ccf672fc' # Drinks
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: 1
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:212dd363-6e33-43f3-8dc4-ba56ccf672fc' # Drinks
  restrictedLocationSubpath: null
  selectionLabel: 'Add a drink image'
  showCardsInGrid: false
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:212dd363-6e33-43f3-8dc4-ba56ccf672fc' # Drinks
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
