dateModified: 1719852679
elementSources:
  craft\elements\Category:
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'group:2e87982a-f266-4d1f-8c83-0cfb7b7f876b' # Drink Styles
      tableAttributes:
        - status
        - 'field:c130f4c5-0f8d-42e3-b1ac-afac0e8a6664' # Style Description
        - uri
        - link
      type: native
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - authors
        - link
        - 'field:b3c51b0c-7e1b-4176-8ba8-8528bde26f6c' # Drink Image
      type: native
    -
      key: singles
      type: native
    -
      heading: Channels
      type: heading
    -
      key: 'section:58cefc9f-ebfd-4628-add4-86a074a83515' # Drinks
      type: native
    -
      key: 'section:78f0dd7b-6de8-4b0d-819e-73d8058a3ab8' # News
      type: native
    -
      heading: ''
      type: heading
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:643330bf-b225-42f9-b7d5-faab81f079b6' # About Crafty Coffee
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
email:
  fromEmail: dwoodhouse1995@gmail.com
  fromName: 'My Example Craft Site'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  drinks:
    hasUrls: true
    name: Drinks
    settings:
      path: '@webroot/images/uploads/drinks'
    type: craft\fs\Local
    url: '@web/images/uploads/drinks'
meta:
  __names__:
    1b26b7bc-e925-4dd8-a6bb-ee9be5c52691: 'Date Added' # Date Added
    2e87982a-f266-4d1f-8c83-0cfb7b7f876b: 'Drink Styles' # Drink Styles
    3c414850-4665-4a4f-b8ea-808d53b4aac0: '840x200 Thumb' # 840x200 Thumb
    3db29b52-7be8-44c0-970a-1cdab90bc2df: Homepage # Homepage
    3de40e44-cc90-46df-9951-cd2967879877: 'Page Intro' # Page Intro
    6cda0386-d180-4ed4-8c09-99c03cf10e29: 'Public Schema' # Public Schema
    6e6b28f5-2e82-4303-8eff-8837bb14f8e9: Simple # Simple
    6ef2eb7d-3ae5-4f26-ba02-1de0c237a427: 'Drink Recipe' # Drink Recipe
    6fedee50-cce7-483e-b10d-5e0dc15ffc44: 'Drink Style' # Drink Style
    8b1872cf-5155-48fb-9b6f-6e6e23b0350f: Excerpt # Excerpt
    9ed3094f-55b3-4d74-b89d-e15f66952941: 'News Body' # News Body
    9f57a2d5-bcb2-4337-913c-0fab81f1b22d: 'Steps Title' # Steps Title
    19a20edf-4a89-46a8-aa59-3fcca62644f2: 'My Example Craft Site' # My Example Craft Site
    36d05999-7f67-4308-9244-582978fb678c: Subtitle # Subtitle
    38a4e35d-28f0-4109-91a7-bb170b615556: 'About Crafty Coffee' # About Crafty Coffee
    47c62729-74d4-45fd-9d41-495d616c05bc: Recipes # Recipes
    58cefc9f-ebfd-4628-add4-86a074a83515: Drinks # Drinks
    74b9a02e-68ac-404e-90d4-df8fae2fde3e: Recipes # Recipes
    78f0dd7b-6de8-4b0d-819e-73d8058a3ab8: News # News
    81a3ad2a-fa5a-4a58-b624-26c48a8c30bd: 'Recipe Image' # Recipe Image
    84b2badb-c279-430a-a3cd-dae9df7f4ffb: 'Recipe Contents' # Recipe Contents
    085f7a35-e3a5-45d5-93de-bf7f670d794d: Homepage # Homepage
    212dd363-6e33-43f3-8dc4-ba56ccf672fc: Drinks # Drinks
    390b5f78-90ea-46fe-a0d3-31cfe4a41d7a: 'My Example Craft Site' # My Example Craft Site
    695a12c8-dbbd-4d04-8a61-b1ead97c70e1: 'Recipe Ingredients' # Recipe Ingredients
    720a0d42-0409-41a0-a7c1-59a0ffb257d2: 'Recipe Copy' # Recipe Copy
    67640af0-a4f7-410d-9151-f8971eb45f5b: 'Tip Content' # Tip Content
    95053f16-aaf0-4d78-b756-1b4871f0bebc: Image # Image
    253439b9-b499-4b2a-abe7-f18252d117fe: 'Recipe Steps' # Recipe Steps
    643330bf-b225-42f9-b7d5-faab81f079b6: 'About Crafty Coffee' # About Crafty Coffee
    965316bd-23a3-4bff-803c-ad8b7803430f: News # News
    80170955-ae12-4281-b702-d6506a4411df: Drinks # Drinks
    b003d9ec-8e06-4bd9-8e6e-5daf3ae13d20: 'Steps Content' # Steps Content
    b3c51b0c-7e1b-4176-8ba8-8528bde26f6c: 'Drink Image' # Drink Image
    bc41b505-8779-47a2-9a9e-228612cff1d4: Introduction # Introduction
    c9e54129-94b5-4f8e-ae20-782487337285: 'Recipe Tip' # Recipe Tip
    c130f4c5-0f8d-42e3-b1ac-afac0e8a6664: 'Style Description' # Style Description
    ca63383b-0341-45da-9e37-658b0e470084: Ingredients # Ingredients
    d571929a-8bce-4069-aa6e-b9ad3439ee79: 'Body Content' # Body Content
    efe2c520-bc92-4dd3-8134-6a97f4c31f20: 'Page Copy' # Page Copy
    f1a8441d-e7da-431f-8aea-821774aa6852: 'Image Caption' # Image Caption
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.1.0.1
system:
  edition: pro
  live: true
  name: 'My Example Craft Site'
  retryDuration: null
  schemaVersion: 5.0.0.21
  timeZone: Europe/London
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
