defaultPlacement: end
enableVersioning: true
entryTypes:
  - 085f7a35-e3a5-45d5-93de-bf7f670d794d # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  390b5f78-90ea-46fe-a0d3-31cfe4a41d7a: # My Example Craft Site
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
